name: Node.js CI

on:
  push:
    branches: [ "ci", "main" ]
  pull_request:
    branches: [ "main", "ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js environment and cache dependencies
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Change directory 
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    # Build the project
    - name: Build project
      run: |
        cd api
        npm run build --if-present

    # Run tests
    - name: Run tests
      run: |
        cd api
        npm test
